name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & lint frontend
        run: |
          cd frontend
          npm ci
          npm run lint

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & test backend
        run: |
          cd backend
          npm ci
          npm test

  ai-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install AI deps
        run: |
          cd ai-service
          pip install -r requirements.txt

      - name: Smoke‑test AI service
        run: |
          cd ai-service
          echo "no tests yet"
