name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Install frontend deps
        run: npm ci
      - name: Lint frontend
        run: npm run lint

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Install backend deps
        run: npm ci
      - name: Run backend tests
        run: npm test

  ai-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install AI deps
        run: pip install -r ai-service/requirements.txt
      - name: Dummy test
        run: echo "no tests yet"
