name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Show files for debug
        run: |
          ls -R .
      - name: Install & lint
        run: |
          cd frontend
          npm ci
          npm run lint

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Show files for debug
        run: |
          ls -R .
      - name: Install & test
        run: |
          cd backend
          npm ci
          npm test

  ai-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Show files for debug
        run: |
          ls -R .
      - name: Install AI deps
        run: |
          cd ai-service
          pip install -r requirements.txt
      - name: Smoke test
        run: |
          cd ai-service
          echo "OK"
