name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Show workspace files
        run: |
          echo "PWD=$(pwd)"
          ls -R .

      - name: Install & lint frontend
        run: |
          cd frontend
          npm install
          npm run lint

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Show workspace files
        run: |
          echo "PWD=$(pwd)"
          ls -R .

      - name: Install & test backend
        run: |
          cd backend
          npm install
          npm test

  ai-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Show workspace files
        run: |
          echo "PWD=$(pwd)"
          ls -R .

      - name: Install AI dependencies
        run: |
          pip install --upgrade pip
          pip install -r ai-service/requirements.txt

      - name: Smoke‑test AI modules
        run: |
          python -c "import nlp_model; print('nlp_model import OK')"
          python -c "import rl_scheduler; print('rl_scheduler import OK')"
